services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MYSQL_DATABASE=hi_meow'
      - 'MYSQL_USER=admin'
      - 'MYSQL_PASSWORD=1234'
      - 'MARIADB_ROOT_PASSWORD=1234'
    ports:
      - '3306:3306'