spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/hi_meow
    username: admin
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  mvc:
    cors:
      allowed-origins: http://localhost:80,http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: '*'
      allow-credentials: true
      max-age: 3600

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  show-actuator: false
  packages-to-scan: com.annyang
  paths-to-exclude: /health

jwt:
  secret: local-development-secret-key-that-is-at-least-32-characters-long
  expiration: 86400  # 24시간

